### ISSUE TITLE
 Can Flocker do disk space limitation and replication of data volume? 

### ISSUE THREAD

**Issue by allencloud** [ClusterHQ/flocker#1268]
Hi, 

I am a freshman of Flocker. Honestly, I am attracted by it with the description of <strong>data volume manager<strong>.

Now I wonder if Flocker can do disk space limitation and replication of data volume? As we all konw when we use devicemapper storage driver to limit the disk space of container, actually it will not take data volume and bind mount into consideration? However, data volume is the most useful storage directory of a data storage container, such as mysql, mongo,...

Anything helps.
Thanks in advance.

**Comment by binocarlos** [comment]
Hey,

Flocker can do both disk space limitation and replication.  We are currently working on an upcoming release (0.4.0) which has a REST api which enables you to create datasets.

One of the properties of a dataset in the REST api is 'maximum_size' - this controls the size of the filesystem in the underlying data volume which means the size limitation still works from inside the container.

Migration is the classic use case for the ZFS storage backend.  When you use flocker to deploy a container with a named volume, flocker will check the state of the cluster to see if the volume already exists elsewhere.

If it does exist elsewhere - Flocker will migrate the data to the new host (using ZFS snapshots). 
We are also working on a block device backend for OpenStack, the classic use case for which is High Availability.

**Comment by allencloud** [comment]
Thanks, Binocarlos.

That sounds great. space limitation I can understand your way.

But in the aspect of  replication, just one confusion.
Can ZFS storage backend  use ZFS snapshot to backup without the interrupt of available time of the  living container?  In a traditional way of filesystem, I cannot backup the mysql storage data lively in /var/lib/mysql using compress into a .tar. If i did this, probably I can not recover a mysql server with the data in .tar.

Thanks

**Comment by binocarlos** [comment]
@allencloud flocker does what is called a 2 phase push.

This means that the first ZFS snapshot is taken and migrated while the container is still running.  The first phase will push the majority of the data.

Once the first push has complete - flocker will stop connections to the container (using iptables) and then complete the second push.  The second push is normally very small (Mbs) and fast (seconds) because it is only the diff from the first.  

So the answer is that there is a small interrupt of the living container but it is minimised because of the 2 phase push.

**Comment by binocarlos** [comment]
Closing this issue now - please re-open if you have further questions...
