### ISSUE TITLE
Build Errors - openssl

### ISSUE THREAD

**Issue by vaibhavkhanduja** [ClusterHQ/flocker#1330]
I am getting build errors while compiling flocker for repository flocker-emc and branch feat_xio_emc. 

Steps to recreate:
a) clone repository
b) vagrant up
c) vagrant ssh
d) cd /vagrant 
e) tox .

Any help is appreciated.

Errors look like:

 gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c -o build/temp.linux-x86_64-2.7/src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.o
    src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:216:25: fatal error: openssl/aes.h: No such file or directory
     #include <openssl/aes.h>
                             ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
    Command "/vagrant/.tox/sphinx/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-IX20By/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gkwNcF-record/install-record.txt --single-version-externally-managed --compile --install-headers /vagrant/.tox/sphinx/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-IX20By/cryptography

**Comment by binocarlos** [comment]
Hi,

It looks like the problem is that you are missing the OpenSSL development headers - `apt-get install libssl-dev` on Ubuntu and `yum install openssl-devel` on RH, CentOS etc

There may be some other non-python dependencies that are required (libffi development headers for example).  You can see what the dependencies are needed by each platform by looking in the Dockerfiles: 

[Ubuntu 14.04](https://github.com/ClusterHQ/flocker/blob/master/admin/build_targets/ubuntu-14.04/Dockerfile#L10)
[CentOS 7](https://github.com/ClusterHQ/flocker/blob/master/admin/build_targets/centos-7/Dockerfile#L10)
[Fedora-20](https://github.com/ClusterHQ/flocker/blob/master/admin/build_targets/fedora-20/Dockerfile#L8)

Hope this helps!

**Comment by vaibhavkhanduja** [comment]
The main culprit over here the cryptography package … it has dependency on open-ssl and libffi 

https://cryptography.io/en/latest/installation/

I also ran into issues with a bug in the same package 

https://bugs.launchpad.net/openstack-gate/+bug/1446882

The bug  has a workaround …

**Comment by binocarlos** [comment]
Hey,

thanks for your investigations :-)

So, have you installed open-ssl / libffi? If yes, have they had an effect on the original error?

**Comment by vaibhavkhanduja** [comment]
Hi

I followed the steps as given in above link and the bug. I am able to compile anf run test case for loop back driver. I still have to test tux but I believe that should work too.

Thanks
