### ISSUE TITLE
Error when use volumes_from in docker_compose.yml

### ISSUE THREAD

**Issue by fernandoneto** [ClusterHQ/flocker#1700]
Hi

Im just make some test's in your tutorial but when i edit docker_compose.yml to be like this
![compose](https://cloud.githubusercontent.com/assets/6515784/8280702/aabf5e24-18d7-11e5-9be8-d44228256cfe.png) i get an error saying volumes_from is not a valid command.
![error](https://cloud.githubusercontent.com/assets/6515784/8280725/ede5786e-18d7-11e5-9f0e-915f8267aa11.png). 

what i want to do is create a data container only that will be able to share a volume with all container in the cluster independently wich host are they running

**Comment by itamarst** [comment]
Hi,

1. Unfortunately at this point in time we only support a subset of the compose language.
2. The way we would probably want to do this requirement is to have a dataset that can be shared by all containers in the cluster, rather than using `volumes_from`. And while that is theoretically possible in some storage backends (though none we support currently), it is not currently supported by our software.

Our product team will note your specific requirements as part of the planning process for future releases, so thanks for filing the issue and explaining your motivation.

What sort of data would you want to store in this volume, and what applications would be running in the container and accessing it?
What kind of data would you be putting in a volume

**Comment by pedros007** [comment]
@itamarst I have the same use case as @fernandoneto.  I would like to store imagery in a volume which is shared by two or more containers.  Let's say one container is a web-app which needs read-only access to `/data`.  Another container is a backend service which runs long-running image processing tasks to create derived images written to `/data`.

**Comment by wallnerryan** [comment]
Closing as we do not plan to support the Container API after 1.11. Continent can safely be shutdown and you should use Docker CLI and our Docker Plugin instead.
