### ISSUE TITLE
Install flocker encounter "clusterhq-flocker-node : Depends: docker.io (>= 1.3.0) but it is not going to be installed"

### ISSUE THREAD

**Issue by coolljt0725** [ClusterHQ/flocker#1851]
Hi all, when I install the flocker on ubuntu 14.04 follow the steps from https://docs.clusterhq.com/en/1.1.0/install/install-node.html 
I encountered the error
<pre><code>Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clusterhq-flocker-node : Depends: docker.io (>= 1.3.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.</code></pre>
and I have installed docker version 1.7.1. 
Anyone can help?

**Comment by lukemarsden** [comment]
Hi there, thanks for trying Flocker!

We are aware of this issue and it has already been fixed in master. I believe that our 1.1.1 release will contain the fix, and I believe that release will be done (hopefully) later this week, so please watch out for that and then try again.

Meanwhile, there are some workarounds documented in the comments on [this issue](https://clusterhq.atlassian.net/browse/FLOC-2447).

Out of interest, what are you thinking of using Flocker for? What kind of applications/databases, how big are they, and on what infrastructure/cloud provider?

Thanks!
Luke

**Comment by lukemarsden** [comment]
By the way @coolljt0725, you can sign up for email updates on Flocker releases by signing up for email updates at in the footer of our website at https://clusterhq.com/

**Comment by coolljt0725** [comment]
@lukemarsden  Thanks for your help
>what are you thinking of using Flocker for? What kind of applications/databases, how big are they, and on what infrastructure/cloud provider?
I'm interested in Flocker. I just trying the the flocker and see what it can do and how it works.

**Comment by lukemarsden** [comment]
You can now install Flocker alongside any version of Docker, @coolljt0725.
