### ISSUE TITLE
[Discuss Flock Functionality]:

### ISSUE THREAD

**Issue by moypray** [ClusterHQ/flocker#1890]
Hi, now we investigate flocker and to see if it meets some requirement in my scenario. Now I just know the high level design draft of flocker.
Could you help me to check this table?

<======= requirement =====>   Zfs Backend(Yes,or No to support)    OpenStack BackEnd( Yes or No)
a. Access Control of Volumes.
 (settings of what some nodes could access 
   but others couldn't) 

b. Shared between containers 
   in one Node at same time    ---------------------- -- Yes       ------------------------------ ???

c. Shared accross Nodes at same time --------------- No?

d. Disk/volume quota(limit the disk/volume)  -----------yes???

And another problem is that service control is one node distribution, what if service control crash?? or could service control run in muti-node(cloud) mode?

Thanks very much~

**Comment by itamarst** [comment]
One unmentioned difference is that the ZFS backend is experimental and much less likely to actually work or get bugs fixed in its current form. At some future point it may get rewritten.

As far as the ones you mention:

Neither backend supports access control at the moment. I imagine for OpenStack you could manage out-of-band somehow by having different OpenStack credentials on different nodes, but that's just a guess.

You can have multiple containers access same dataset on any backend as long as:
* You're managing the containers yourself, rather than with Flocker Container API.
* All containers are on the same node.
What is your use case that requires this?

None of the backends support access to same dataset from multiple nodes.

I think both backends support maximum size, yes.

At the moment the control service is a single point of failure, yes. This will likely change in the future, but when exactly depends on how this ends up being prioritized on our product roadmap.

**Comment by moypray** [comment]
Hi @itamarst , we don't plan to use flocker-deploy to distribute containers. We only want to use flocker-plugin and control service data volumes.   The project is just like the project in Lab Project "https://docs.clusterhq.com/en/1.1.0/labs/docker-plugin.html". The purpose of using flocker volume-plugin is to meet the requirement to share and move data volumes across nodes free and easily.

And we continue to use Docker API to distribute containers, just like run "docker run -v xxx:/var/lib/mysql  --volume-driver=flocker  mysql:3.4.5"  command ( actually, we have our docker client, just send REST API to docker daemon, that is why we won't use flocker-deploy).

As we wanna use docker REST API, so we do not plan to use Flocker Container API.

Does it work???

Thanks

**Comment by moypray** [comment]
And more, how does Flocker Container API works?

I guess the work flow like this:
User run client CLI to send FLocker Container API to Flocker-container-agent, and container agent check volumes and sync volumes between control service.  When volume data is mount done, will send Docker REST API to docker Deamon?

User  -->  Flocker Container API   ----->  Docker Deamon
                       |-------> Control service to sync volumes??

**Comment by moypray** [comment]
And more, how does container API work?
Could you tell the work flow of starting a container?

thanks again

**Comment by moypray** [comment]
I have setup this environment, something wrong with my config.
thanks

**Comment by lukemarsden** [comment]
Hi @moypray - thanks for trying Flocker! I'd love to help you diagnose the issue with your config, perhaps you can post specific details here, including your `agent.yml`, and describe what your expected behaviour is, and what the actual behaviour you're seeing is?

I'd recommend using the docker plugin as you plan to over our containers API. We plan to deprecate the containers API soon and the docker plugin is the future.
