### ISSUE TITLE
Docker plugin opts doc

### ISSUE THREAD

**Issue by wangqiang8511** [ClusterHQ/flocker#2143]
In docker 1.9, you can specify opts when you create volumes.
Currently, what kind of opts flocker support?
profile=gold?
Can we add volume size in opts as well?

Can we add more docs about how to pass opts with docker plugin?

**Comment by wallnerryan** [comment]
Flocker _will_ support profiles and other options. Today it does not. We wil update this issue when support for such options becomes available.

**Comment by lukemarsden** [comment]
Thanks for the feature request! You can track progress on this feature here: https://clusterhq.atlassian.net/browse/FLOC-3417

**Comment by chosenken** [comment]
Not sure if I should comment here or elsewhere, but would it be possible to pass in Tags to EBS volumes?  I would like to be able to specify additional tags when creating volumes automatically, like:

```-o ebsTags=TagName1:TagValue,TagName2:TagValue```

**Comment by itamarst** [comment]
The latest version of Flocker now supports specifying profiles on the command-line: https://docs.clusterhq.com/en/1.7.2/control/plugin/index.html#storage-profiles

**Comment by itamarst** [comment]
@chosenken thanks for the feature request! I pinged our product team about it.

**Comment by lukemarsden** [comment]
@chosenken Flocker supports metadata per dataset; essentially key-value pairs, just like EBS tags. These are stored in Flocker itself rather than the backend. I wonder if your use case could be satisfied by adding flocker metadata support in the Flocker plugin for Docker? That way you'd be able to set -o metadata=TagName1:TagValue,TagName2:TagValue. That way you wouldn't be dependent on an EBS specific configuration, and would be free to move your workloads around between different runtime environments in the future.

I'm interested to know what you think of that. Is there something you need to do with EBS tags where you'd need to query them directly using the AWS APIs?

**Comment by chosenken** [comment]
@lukemarsden We were mainly looking at using flocker on AWS with ESB volumes, and would like to see what the purpose of a volume is just from the Amazon Volume UI.  It's more of a "easy of life" thing, we could sort on volumes that we tagged based on our tags.  So if we wanted to set a tag such as purpose, we could then sort on Database, Logs, etc.

**Comment by wallnerryan** [comment]
@wangqiang8511 https://clusterhq.atlassian.net/browse/FLOC-3417 was merged into master, which means sizes passed to docker plugin `--opts` like `-o size=10GB` will be available in our next release.

**Comment by wallnerryan** [comment]
update: specifying size via `docker opts` was released as part of our most recent release 1.9. https://docs.clusterhq.com/en/1.9.0/releasenotes/index.html#v1-9-0

**Comment by wallnerryan** [comment]
docs for size and profile opts should be there now. Closing.
