### ISSUE TITLE
flocker container-agent log file is very large?

### ISSUE THREAD

**Issue by ttllyy** [ClusterHQ/flocker#2236]
exec /usr/sbin/flocker-container-agent --logfile=/var/log/flocker/flocker-container-agent.log

flocker-container-agent.log file size increased very quickly. No operation, file is inc 400M+ every day.

**Comment by wallnerryan** [comment]
Hi @ttllyy, the container agent talks to the docker daemon very frequently, there fore when you log to a file instead of using something like journald it can build up quickly. You can use something like [logrotate](http://linux.die.net/man/8/logrotate) to help with this. Or we recommend running the agents with something like systemd which uses journald is what most installations use.

**Comment by wallnerryan** [comment]
re-opening for now for discussion

**Comment by itamarst** [comment]
Hi,

We are planning on eventually removing Flocker's container API, in favor of e.g. the Docker plugin. In the short term that means we are going to make the container agent optional, since it shouldn't be necessary to run it if you're using the Docker plugin for Flocker. As such we're not putting much effort into fixing issues in the container agent, since it will become obsolete in near future.

I believe that on Ubuntu the files will get rotated, and eventually deleted (see the upstart config file for the service).
