### ISSUE TITLE
reading directory .: Input/output error with multi containers 

### ISSUE THREAD

**Issue by AI-PaaS** [ClusterHQ/flocker#2711]
Hi:
 I am following the marathon ha demo. i am using the openstack cinder as the backend,  i can run one docker container in one node, then write somethine in the docker volume. after i stop the contianer, then i start another container with the same volume, i can get the writted text.

but, if i **do not** stop the first one container, then the second also can get the text, but the first will throw error"reading directory .: Input/output error"

The result is same in marathon.

**Comment by wallnerryan** [comment]
Hi @AI-PaaS I need a few more details to help. 
What OS are you running?
Are both containers running on the same node? 
What docker images are you using in your examples? 
Also what version of flocker / mesos/ marathon are you using?

**Comment by AI-PaaS** [comment]
What OS are you running?  
    We use centos 7.0.
Are both containers running on the same node? 
  No, on two node.
What docker images are you using in your examples? 
   docker versoin:1.10.3, image:redis:3.0.6
Also what version of flocker / mesos/ marathon are you using?
  flocker: 1.10.2, mesos: 0.28.0, marathon: 0.15.3

**Comment by wallnerryan** [comment]
@AI-PaaS 

So flocker volumes are 1:1 when it comes to containers. Meaning that only one container can access them at one time. You are getting an `error"reading directory .: Input/output error"` on the first container because it no longer has access to the volume because it can only be mounted on one host at a time.

Are you using the Docker containerizer with Mesos? 

The expected output of this would be the the second container being deployed on a different node should time out trying to start since the first one is still using it. If thats not the case, then there is likely a bug.

**Comment by wallnerryan** [comment]
@AI-PaaS yes, this is because there is 1:1 mapping from container:flocker-volume
