### ISSUE TITLE
 /dev/mapper/mpathu is already mounted on /path/

### ISSUE THREAD

**Issue by akhilcalsoft** [ClusterHQ/flocker#2849]
Hi Wallner,

I am writing flocker driver but I am stuck at below error:

```
`7f26dac5-71d9-4149-af6e-7c9a8d7a7334 -> /2/6/41
2016-06-29 14:44:17.975105Z
  action_type: 'flocker:node:in_parallel'
  action_status: 'failed'
  exception: 'twisted.internet.defer.FirstError'
  reason: 'FirstError[#35, [Failure instance: Traceback: <class \'flocker.node.agents.blockdevice_manager.MountError\'>: <MountError(blockdevice=FilePath(\'/dev/dm-1\'), mountpoint=FilePath(\'/flocker/a9608f4d-01c1-4951-81dd-f833702e8df6\'), source_message=u"Command \'[\'mount\', \'/dev/dm-1\', \'/flocker/a9608f4d-01c1-4951-81dd-f833702e8df6\']\' returned non-zero exit status 32\
        |  mount: /dev/mapper/mpathu is already mounted or /flocker/a9608f4d-01c1-4951-81dd-f833702e8df6 busy\
        |         /dev/mapper/mpathu is already mounted on /flocker/a9608f4d-01c1-4951-81dd-f833702e8df6\
        |  ")>
        |  /opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
        |  /opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py:119:run
        |  /opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py:119:<genexpr>
        |  /opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py:90:run_state_change
        |  --- <exception caught here> ---
        |  /opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
        |  /opt/flocker/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:623:run
        |  /opt/flocker/lib/python2.7/site-packages/flocker/node/agents/blockdevice_manager.py:300:mount
        |  ]]'

7f26dac5-71d9-4149-af6e-7c9a8d7a7334 -> /2/7
2016-06-29 14:44:17.975780Z
  message_type: 'eliot:traceback'
  exception: 'twisted.internet.defer.FirstError'
  reason: 'FirstError[#35, [Failure instance: Traceback: <class \'flocker.node.agents.blockdevice_manager.MountError\'>: <MountError(blockdevice=FilePath(\'/dev/dm-1\'), mountpoint=FilePath(\'/flocker/a9608f4d-01c1-4951-81dd-f833702e8df6\'), source_message=u"Command \'[\'mount\', \'/dev/dm-1\', \'/flocker/a9608f4d-01c1-4951-81dd-f833702e8df6\']\' returned non-zero exit status 32\
        |  mount: /dev/mapper/mpathu is already mounted or /flocker/a9608f4d-01c1-4951-81dd-f833702e8df6 busy\
        |         /dev/mapper/mpathu is already mounted on /flocker/a9608f4d-01c1-4951-81dd-f833702e8df6\
        |  ")>
        |  /opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
        |  /opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py:119:run
        |  /opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py:119:<genexpr>
        |  /opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py:90:run_state_change
        |  --- <exception caught here> ---
        |  /opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
        |  /opt/flocker/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:623:run
        |  /opt/flocker/lib/python2.7/site-packages/flocker/node/agents/blockdevice_manager.py:300:mount
        |  ]]'
  traceback: 'Traceback (failure with no frames): <class \'twisted.internet.defer.FirstError\'>: FirstError[#35, [Failure instance: Traceback: <class \'flocker.node.agents.blockdevice_manager.MountError\'>: <MountError(blockdevice=FilePath(\'/dev/dm-1\'), mountpoint=FilePath(\'/flocker/a9608f4d-01c1-4951-81dd-f833702e8df6\'), source_message=u"Command \'[\'mount\', \'/dev/dm-1\', \'/flocker/a9608f4d-01c1-4951-81dd-f833702e8df6\']\' returned non-zero exit status 32\
           |  mount: /dev/mapper/mpathu is already mounted or /flocker/a9608f4d-01c1-4951-81dd-f833702e8df6 busy\
           |         /dev/mapper/mpathu is already mounted on /flocker/a9608f4d-01c1-4951-81dd-f833702e8df6\
           |  ")>
           |  /opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
           |  /opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py:119:run
           |  /opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py:119:<genexpr>
           |  /opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py:90:run_state_change
           |  --- <exception caught here> ---
           |  /opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
           |  /opt/flocker/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:623:run
           |  /opt/flocker/lib/python2.7/site-packages/flocker/node/agents/blockdevice_manager.py:300:mount
```
`
Please let me know, why is it mounting again and again ?

**Comment by akhilcalsoft** [comment]
Hi Wallner,

I have debugged the issue and below is my understanding:
`get_device_path` is returning `'/dev/mapper/mpathu' `path and disk is mounted with this path.
but flocker is trying to mount it again with real path` /dev/dm-1`( **/dev/mapper/mpathu is symlink of /dev/dm-1**).

And get_mounts is returning  sdiskpart(device='/dev/mapper/mpathu', mountpoint='/flocker/a9608f4d-01c1-4951-81dd-f833702e8df6', fstype='ext4', opts='rw,relatime,stripe=256,data=ordered') **not /dev/dm-1**.

Please let me know, how can i implement mpath ?

**Comment by wallrj** [comment]
Hey @akhilcalsoft 

This sounds like a similar situation to one documented in `_get_device_path_virtio_blk` in our Cinder driver code:
 * https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/cinder.py#L621
````
        # Return the real path instead of the symlink to avoid two problems:
        #
        # 1. flocker-dataset-agent mounting volumes before udev has populated
        #    the by-id symlinks.
        # 2. Even if we mount with `/dev/disk/by-id/xxx`, the mounted
        #    filesystems are listed (in e.g. `/proc/mounts`) with the
        #    **target** (i.e. the real path) of the `/dev/disk/by-id/xxx`
        #    symlinks. This confuses flocker-dataset-agent (which assumes path
        #    equality is string equality), causing it to believe that
        #    `/dev/disk/by-id/xxx` has not been mounted, leading it to
        #    repeatedly attempt to mount the device.
````
In that function we check for the symlink and then return the `realpath` or target path of the symlink.

Let me know if this helps.

**Comment by akshaycalsoft** [comment]
You are right, I am facing similar issue. I have tried your suggestion as well (Return realpath) but it does not help here.

I tried returning /dev/mapper/mpath*** or /dev/dm-* device, but no luck.

Unlike `/dev/disk/by-id/xxx, for multipath device mount point in /proc/mounts, it uses symbolic link(/dev/mapper/mpath*** ) and not realpath(/dev/dm-*) /proc/mounts shows /dev/mapper/mpathu is mounted at /flocker/a9608f4d-01c1-4951-81dd-f833702e8df6
It seems that flocker code assumes device in /proc/mounts as realpath and its logic fails for multipath dev resulting mount retries.

Whether multipath device is supported by Flocker? If so, can you please suggest any workaround.

**Comment by akhilcalsoft** [comment]
You are right, I am facing similar issue. I have tried your suggestion as well (Return realpath) but it does not help here.

I tried returning /dev/mapper/mpath*** or /dev/dm-* device, but no luck.

Unlike `/dev/disk/by-id/xxx, for multipath device mount point in /proc/mounts, it uses symbolic link(/dev/mapper/mpath*** ) and not realpath(/dev/dm-*) /proc/mounts shows /dev/mapper/mpathu is mounted at /flocker/a9608f4d-01c1-4951-81dd-f833702e8df6
It seems that flocker code assumes device in /proc/mounts as realpath and its logic fails for multipath dev resulting mount retries.

Whether multipath device is supported by Flocker? If so, can you please suggest any workaround.

**Comment by wallrj** [comment]
I think this:
 * https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/blockdevice.py#L1819

...is probably where it's going wrong.

We're looking for the `IBlockDeviceAPI.get_device_path` in `raw_state.system_mounts` but system_mounts is populated from `IBlockDeviceManager.get_mounts`
 * https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/blockdevice_manager.py#L308

I'd have thought things should work if your driver returned the device path that was discovered by `psutil.disk_partitions()` .

Perhaps there's some subtle difference when using multi-path devices.

Let me know what psutil.disk_partitions() reports for your mounted multi-path device.

At one time we were considering setting ext4 UUIDs that match the Flocker dataset_id.
That would allow us to unambiguously mount the correct device using `mount UUID=aaa-bbb-ccc /flocker/aaa-bbb-ccc`.

See:
 * https://clusterhq.atlassian.net/browse/FLOC-2329
 * https://github.com/ClusterHQ/flocker/pull/1653

We were considering that to overcome difficulties in reliably  identifying the correct device path for AWS EBS attached volumes.

We rejected  / postponed it because:
 * there is still the difficulty of selecting the correct device for the `mkfs` step (although perhaps that doesn't affect your multipath code).
 * we had difficulty writing a bullet-proof upgrade mechanism; to stamp existing dataset filesystems with the correct UUID.

You could try modifying blockdevice.py to label the filesystem.

A separate point is that last year I did some work on a proof-of-concept EMC VNX driver for Flocker, but I didn't get so far as setting up multipath devices:
 * https://github.com/ClusterHQ/flocker-vnx-driver/blob/master/flocker_emc_vnx_driver/_driver.py#L442

I was told at the time that I'd need to use EMC PowerPath because the native Linux tools didn't support automatic failover. 
I'm not sure if that's still the case.

Anyway, it'd be great to hear how you get on.

-RichardW.

**Comment by shay-berman** [comment]
Hello @wallrj 

I am writing Flocker driver for IBM storage and I am facing the same issue.
My Flocker driver is working well and passed all the "minimal functional tests" but when I run it on a real Flocker environment and trigger "flockerctl create..." the dataset is stuck on "detached" state.

In the log there is MountError say  "mount: /dev/mapper/36001738cfc9035e8000000000008f11c already mounted or /flocker/a11cce9a-dc63-4935-89af-8fe204e536bc busy"

It looks like Flocker try to mount it again. 
Here is the relevant line from the /etc/mtab
/dev/mapper/36001738cfc9035e8000000000008f11c /flocker/a11cce9a-dc63-4935-89af-8fe204e536bc ext4 rw 0 0

Somehow the device is /dev/mapper/36001738cfc9035e8000000000008f11c instead of the /dev/dm-0 (note that get_device_path interface return the /dev/dm-0 device and not the /dev/mapper/36001738cfc9035e8000000000008f11c.

Any idea?

Full exception : 
> 88de6ddf-9329-4001-b46e-6b56745ed258 -> /2/7
2016-07-05 19:28:05.684811Z
  message_type: 'eliot:traceback'
  exception: 'twisted.internet.defer.FirstError'
  reason: 'FirstError[#0, [Failure instance: Traceback: <class \'flocker.node.agents.blockdevice_manager.MountError\'>: <MountError(blockdevice=FilePath(\'/dev/dm-0\'), mountpoint=FilePath(\'/flocker/a11cce9a-dc63-4935-89af-8fe204e536bc\'), source_message=u"Command \'[\'mount\', \'/dev/dm-0\', \'/flocker/a11cce9a-dc63-4935-89af-8fe204e536bc\']\' returned non-zero exit status 32\
        |  mount: /dev/mapper/36001738cfc9035e8000000000008f11c already mounted or /flocker/a11cce9a-dc63-4935-89af-8fe204e536bc busy\
        |  mount: according to mtab, /dev/mapper/36001738cfc9035e8000000000008f11c is already mounted on /flocker/a11cce9a-dc63-4935-89af-8fe204e536bc\
        |  ")>
        |  /opt/flocker/local/lib/python2.7/site-packages/Twisted-15.1.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:140:maybeDeferred
        |  /opt/flocker/local/lib/python2.7/site-packages/flocker/node/_change.py:119:run
        |  /opt/flocker/local/lib/python2.7/site-packages/flocker/node/_change.py:119:<genexpr>
        |  /opt/flocker/local/lib/python2.7/site-packages/flocker/node/_change.py:90:run_state_change
        |  --- <exception caught here> ---
        |  /opt/flocker/local/lib/python2.7/site-packages/Twisted-15.1.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:140:maybeDeferred
        |  /opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:623:run
        |  /opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice_manager.py:300:mount
        |  ]]'
  traceback: 'Traceback (failure with no frames): <class \'twisted.internet.defer.FirstError\'>: FirstError[#0, [Failure instance: Traceback: <class \'flocker.node.agents.blockdevice_manager.MountError\'>: <MountError(blockdevice=FilePath(\'/dev/dm-0\'), mountpoint=FilePath(\'/flocker/a11cce9a-dc63-4935-89af-8fe204e536bc\'), source_message=u"Command \'[\'mount\', \'/dev/dm-0\', \'/flocker/a11cce9a-dc63-4935-89af-8fe204e536bc\']\' returned non-zero exit status 32\
           |  mount: /dev/mapper/36001738cfc9035e8000000000008f11c already mounted or /flocker/a11cce9a-dc63-4935-89af-8fe204e536bc busy\
           |  mount: according to mtab, /dev/mapper/36001738cfc9035e8000000000008f11c is already mounted on /flocker/a11cce9a-dc63-4935-89af-8fe204e536bc\
           |  ")>
           |  /opt/flocker/local/lib/python2.7/site-packages/Twisted-15.1.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:140:maybeDeferred
           |  /opt/flocker/local/lib/python2.7/site-packages/flocker/node/_change.py:119:run
           |  /opt/flocker/local/lib/python2.7/site-packages/flocker/node/_change.py:119:<genexpr>
           |  /opt/flocker/local/lib/python2.7/site-packages/flocker/node/_change.py:90:run_state_change
           |  --- <exception caught here> ---
           |  /opt/flocker/local/lib/python2.7/site-packages/Twisted-15.1.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:140:maybeDeferred
           |  /opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:623:run
           |  /opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice_manager.py:300:mount
           |  ]]
           |  '

**Comment by akhilcalsoft** [comment]
@wallrj ,

This is output of psutil.disk_partitions():
```
[sdiskpart(device='/dev/sda2', mountpoint='/', fstype='ext3', opts='rw,relatime,data=ordered'), sdiskpart(device='/dev/sda1', mountpoint='/boot', fstype='ext3', opts='rw,relatime,data=ordered'), sdiskpart(device='/dev/mapper/mpathu', mountpoint='/flocker/a9608f4d-01c1-4951-81dd-f833702e8df6', fstype='ext4', opts='rw,relatime,stripe=256,data=ordered')
]
```

And it is executing mount for  /dev/dm-1 which is realpath of /dev/mapper/mpathu.

`source_message=u"Command \'[\'mount\', \'/dev/dm-1\', \'/flocker/a9608f4d-01c1-4951-81dd-f833702e8df6\']\'`

May i know, `get_device_path` is returning `'/dev/mapper/mpathu'` and how flocker is getting /dev/dm-1 path ?

**Comment by wallrj** [comment]
> May i know, get_device_path is returning '/dev/mapper/mpathu' and how flocker is getting /dev/dm-1 path ?

@akhilcalsoft I can't explain that. I've looked through the code again this morning and I can't see any way that you'd end up with `mount /dev/dm-1 /flocker/aaa-bbb-ccc` if `get_device_path` returns `/dev/mapper/mpathu`.

* Are you sure you're running the correct version of the code? Double check the source code in `/opt/flocker/`.
* Did you check the entire error that contains `...source_message=u"Command \'[\'mount\',...` come from? It comes from https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/blockdevice_manager.py#L296 and it should contain the actual `blockdevice` path that was supplied to mount.

Your original message contained the following error (formatted) which showed Flocker attempting to mount `/dev/dm-1` and the `mount` command referring to `/dev/mapper/mpathu` in its error message printed to stderr.

```
MountError(
    blockdevice=FilePath('/dev/dm-1'),
    mountpoint=FilePath('/flocker/a9608f4d-01c1-4951-81dd-f833702e8df6'),
    source_message=u"""
        Command 
            ['mount', '/dev/dm-1', '/flocker/a9608f4d-01c1-4951-81dd-f833702e8df6'] 
            returned non-zero exit status 32
        mount: /dev/mapper/mpathu is already mounted or 
               /flocker/a9608f4d-01c1-4951-81dd-f833702e8df6 busy
               /dev/mapper/mpathu is already mounted on /flocker/a9608f4d-01c1-4951-81dd-f833702e8df6
    """
)
```

I wonder if the problem is caused by the way Flocker creates the filesystem?

In particular, we *do not* partition the block device. 
We run `mkfs -t ext4 -F /dev/xyz` to force the filesysystem onto the raw block device.
 * https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/blockdevice_manager.py#L259

Try performing these steps manually and that you can mount the device.

Hope that helps

**Comment by wallrj** [comment]
@shay-berman See above ^^.  I think my answer applies to your question too. 

PS I'd be happy to join either of you for a shared debugging session if that helps.

**Comment by shay-berman** [comment]
@wallrj 

Now its working

Here is the buggy flow :
1. My get_device_path interface returned the /dev/dm-0 
2. then Flocker mount /dev/dm-0 path to /flocker/a11cce9a-dc63-4935-89af-8fe204e536bc
    BUT when you do "mount /dev/dm-0  /flocker/a11cce9a-dc63-4935-89af-8fe204e536bc"
    in the /etc/mtab it will show up with the /dev/mapper/36001738cfc9035e8000000000008f11c device
3. then Flocker retry to mount it because /dev/dm-0 was not exist in the /etc/mtab file
and it failed because its  /flocker/a11cce9a-dc63-4935-89af-8fe204e536bc is already mounted
This is why i get the mount error in the log.

In order to fix it the get_device_path() should return the /dev/mapper device instead of the /dev/dm-0 device. After fix this I succeeded to create volume via "flockerctl" with out the error and the dataset got to "attached" state.

@wallrj 
Lets improve Flocker so he will handle also /dev/md (returned by get_device_path) and not fail because the linux shows the equivalent /dev/mapper device in the /etc/mtab.
What do you think?  (for example you can use dmsetup status /dev/dm-1 to get the dev mapper device)

**Comment by akhilcalsoft** [comment]
@wallrj 

it is working now.
Real path was returning /dev/dm-1 instead of /dev/mapper/mpathu.

Thanks you so much for your inputs.

**Comment by wallnerryan** [comment]
closing because this seems solved. If there is a seperate issue please open a new one or contact support@clusterhq.com
