### ISSUE TITLE
Can flocker across data centers

### ISSUE THREAD

**Issue by barnettZQG** [ClusterHQ/flocker#2955]
```
docker: Error response from daemon: Timed out waiting for dataset to mount..
```
I have two machines in different data center.Install the flocker service.Single machine when it is available, but the above mistakes after two machines.Flocker does not support across the data center?

**Comment by wallnerryan** [comment]
Where are you running flocker? AWS, Rackspace, GCE? 

In all cases, flocker nodes need to be configured for the correct availability zone and datacenter. Flocker does not currently support cross datacenter mostly because its a limitation on the backend storage systems.

check out FlockerHub and Fli, they do support corss data center with `push` and `pull`.
https://clusterhq.com/flockerhub/introduction/

https://clusterhq.com/register/flockerhub-beta/
