### ISSUE TITLE
CoreOS and GCE support

### ISSUE THREAD

**Issue by rimusz** [ClusterHQ/flocker#980]
CoresOS as OS support
GCE as a cloud provider support

**Comment by adamtheturtle** [comment]
Thanks for your interest in Flocker @rimusz, and sorry it took so long to get back to you. I don't know when these things will be a priority but I can tell you that we are looking into them. You can follow any potential progress on creating Flocker clusters on GCE at https://clusterhq.atlassian.net/browse/FLOC-1149 and on CoreOS at https://clusterhq.atlassian.net/browse/FLOC-1145. There is progress on getting Flocker working with CoreOS and for example described on https://clusterhq.atlassian.net/browse/FLOC-667.

I'm closing this issue because it is covered by the issues mentioned above and others.
